{
 "title": "k6 Load Testing Results Copy",
 "description": "A dashboard for visualizing results from the k6.io load testing tool, using the Prometheus.",
 "time": { "from": "2023-03-14T14:52:31.631Z", "to": "2023-03-14T16:52:31.631Z" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Virtual Users",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "VUs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "k6_vus", "legendFormat": "Virtual Users" },
    { "expr": "k6_vus_max", "legendFormat": "Max Users" }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(k6_http_reqs_total)", "legendFormat": "sum" }
   ]
  },
  {
   "title": "Iterations per second",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(k6_iterations_total[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(k6_data_received_total[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(rate(k6_data_sent_total[$__rate_interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (k6_http_reqs_total{})",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  },
  {
   "title": "max duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(k6_http_req_duration_p99{})"
    }
   ]
  },
  {
   "title": "min duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(k6_http_req_duration_p99{})"
    }
   ]
  },
  {
   "title": "request duration (avg)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(k6_http_req_duration_p99{})"
    }
   ]
  },
  {
   "title": "P95 (avg)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(k6_http_req_duration_p99{})"
    }
   ]
  },
  {
   "title": "K6 latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "quantile(0.95, avg(k6_http_req_waiting_p99{}))",
     "legendFormat": "P95"
    },
    {
     "expr": "quantile(0.90, k6_http_req_waiting_p99{})",
     "legendFormat": "P90"
    }
   ]
  }
 ]
}